name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
          cache-dependency-path: 'integration/**/yarn.lock'
      - name: Install dependencies    
        run: yarn --frozen-lockfile && yarn install:integration
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test & Coverage Report
        timeout-minutes: 4
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test:coverage --ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: yarn semantic-release
